import * as React from "react";
import { Button } from "./ui/primitives";

const STORAGE_KEY = "vsme_agreement_v1";

export function useAgreement() {
  const [showModal, setShowModal] = React.useState(false);

  React.useEffect(() => {
    if (localStorage.getItem(STORAGE_KEY) === "accepted") return;
    fetch("/api/agreement/status")
      .then((r) => r.json())
      .then((data: { accepted: boolean }) => {
        if (data.accepted) {
          localStorage.setItem(STORAGE_KEY, "accepted");
        } else {
          setShowModal(true);
        }
      })
      .catch(() => setShowModal(true));
  }, []);

  const accept = React.useCallback(() => {
    fetch("/api/agreement/accept", { method: "POST" }).catch(() => {});
    localStorage.setItem(STORAGE_KEY, "accepted");
    setShowModal(false);
  }, []);

  return { showModal, accept };
}

export function UserAgreementModal({ onAccept }: { onAccept: () => void }) {
  // Block Escape key — this modal cannot be dismissed without accepting.
  React.useEffect(() => {
    const block = (e: KeyboardEvent) => {
      if (e.key === "Escape") e.preventDefault();
    };
    window.addEventListener("keydown", block, { capture: true });
    return () => window.removeEventListener("keydown", block, { capture: true });
  }, []);

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/85 p-6 backdrop-blur-sm">
      <div
        className="panel flex w-full max-w-2xl flex-col bg-surface-raised shadow-2xl"
        style={{ maxHeight: "88vh" }}
      >
        {/* Header */}
        <div className="shrink-0 border-b border-border px-6 py-4">
          <div className="mb-1 flex items-center gap-3">
            <img src="/icon no bg.png" alt="" className="h-7 w-auto opacity-90" />
            <h2 className="text-base font-semibold tracking-tight">
              Nexum Solutions — User Agreement
            </h2>
          </div>
          <p className="text-xs text-muted-foreground">
            You must read and accept this agreement before using the Value Stream Model Engine.
          </p>
        </div>

        {/* Scrollable body */}
        <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5 text-sm leading-relaxed text-foreground">
          <p className="mb-4 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
            Please read carefully
          </p>

          <section className="space-y-4">
            <p>
              This User Agreement ("Agreement") governs your access to and use of the{" "}
              <strong>Value Stream Model Engine</strong> (the "Application"), developed and owned
              by <strong>Nexum Solutions</strong> and its creator ("Owner"). By clicking "I
              Accept" you agree to be legally bound by every term below. If you do not agree, you
              must not use the Application.
            </p>

            <div>
              <h3 className="mb-1 font-semibold">1. Grant of Access</h3>
              <p>
                Nexum Solutions grants you a limited, non-exclusive, non-transferable right to
                access and use the Application solely for your authorized internal business
                purposes. This right may be revoked at any time.
              </p>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">2. Confidentiality and Non-Disclosure</h3>
              <p>
                All information, data, analyses, reports, outputs, methods, and any other content
                accessed through or generated by the Application is strictly confidential. You
                agree that you will not, directly or indirectly:
              </p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-foreground/90">
                <li>
                  Disclose, communicate, or reveal any content from or about the Application to
                  any third party;
                </li>
                <li>Share access to the Application with any unauthorized person;</li>
                <li>
                  Publish, post, transmit, or otherwise distribute any output or content derived
                  from the Application in any medium or form.
                </li>
              </ul>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">3. Intellectual Property</h3>
              <p>
                The Application and all of its components — including but not limited to its
                software code, design, logic, analytical frameworks, methodologies, user
                interface, and documentation — are the exclusive intellectual property of Nexum
                Solutions and its creator. All rights are reserved. Nothing in this Agreement
                transfers any ownership interest to you. Any unauthorized use, reproduction, or
                distribution of the Application or its contents constitutes an infringement of
                the Owner's rights and may result in legal action.
              </p>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">4. Prohibited Uses</h3>
              <p>You agree that you will not:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-foreground/90">
                <li>
                  Copy, reproduce, reverse-engineer, decompile, disassemble, or create derivative
                  works from the Application or any part of it;
                </li>
                <li>
                  Use the Application for any purpose other than the specific authorized purpose
                  for which access was granted;
                </li>
                <li>
                  Remove, alter, or obscure any proprietary notices, trademarks, or branding
                  within the Application;
                </li>
                <li>
                  Circumvent or attempt to circumvent any security, access controls, or usage
                  tracking within the Application.
                </li>
              </ul>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">5. No Warranties</h3>
              <p>
                The Application is provided "as is" without warranty of any kind, express or
                implied. Nexum Solutions makes no warranty that the Application will be
                uninterrupted, error-free, or that results will be accurate or complete.
              </p>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">6. Limitation of Liability</h3>
              <p>
                In no event shall Nexum Solutions or its creator be liable for any indirect,
                incidental, special, or consequential damages arising out of or in connection
                with your use of, or inability to use, the Application.
              </p>
            </div>

            <div>
              <h3 className="mb-1 font-semibold">7. Entire Agreement</h3>
              <p>
                This Agreement constitutes the entire understanding between you and Nexum
                Solutions regarding your use of the Application and supersedes any prior
                agreements or communications on this subject.
              </p>
            </div>

            <p className="rounded-md border border-border bg-muted/40 px-4 py-3 text-xs text-muted-foreground">
              Unauthorized use, disclosure, copying, or distribution of this Application or its
              outputs may subject you to civil and criminal penalties under applicable law.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="shrink-0 border-t border-border px-6 py-4">
          <div className="flex items-center justify-between gap-4">
            <p className="text-xs text-muted-foreground">
              By clicking <strong>"I Accept"</strong> you confirm that you have read,
              understood, and agree to be bound by this Agreement.
            </p>
            <Button onClick={onAccept} size="md" className="shrink-0 px-6">
              I Accept
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
